# Project information
site_name: Lesotho Health SI Systems Documentation
site_description: "Technical documentation for Lesotho's Health Systems"
site_author: "Ministry of Health"
site_url: "https://github.com/eRegister"

# Copyright
copyright: "Copyright &copy; 2020 Ministry of Health - Lesotho"

# Theme
theme:
  name: "material"
  palette:
    primary: "#2d3479"
    accent: "indigo"
  language: "en"
  features:
    - tabs
  font:
    text: "Roboto"
    code: "Roboto Mono"

# Nagivation
nav:
  - Overview:
      - "index.md"
      - "contacts.md"
  - DHIS2:
      - "User Manual":
          - "dhis2/usermanual.md"
      - "DataSets":
          - "dhis2/intro.md"
          - "dhis2/hts.md"
          - "dhis2/tb.md"
          - "dhis2/tb-indicators.md"
          - "dhis2/tb-validation-rules.md"
          - "dhis2/hiv-care-n-tx.md"
      - "Technical Manual":
          - "dhis2/installation.md"
  - Informed Push:
      - -"informedpush/informedpush.md"
      - "informedpush/informedpusharv.md"
  - eRegister:
      - "User Manual":
          - "ereg/u-intro.md"
      - "Technical Manual":
          - "ereg/intro.md"
          - "ereg/workingwithdockerlocally.md"
          - "ereg/FAQs.md"
          - "ereg/clientregistry.md"
          - "ereg/facilityimplementationchecklist.md"
          - "ereg/automateddeployment.md"
  - COVID-19:
      - "Overview":
          - "covid/Overview.md"
      - "Data Consumption Guidelines":
          - "covid/Indicators.md"
      - "Data Entry Guidelines":
          - "covid/using-web.md"
          - "covid/using-mobile.md"

markdown_extensions:
  - admonition
# EXTENSIONS NOT WORKING - i don't know why. will figure it out

# markdown_extensions:
#   - admonition
#   - codehilite:
#       guess_lang: false
#   - toc:
#       toc_depth : "1-1"
#   - footnotes

# plugins:
#   - search
#   - git-revision-date-localized
#   - mknotebooks
#   - pdf-export:
#       combined: true

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/intrahealth/client-registry
